name: Echo
options:
  bundleIdPrefix: com.xianggui.echo
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  EchoCore:
    path: Packages/EchoCore
  EchoUI:
    path: Packages/EchoUI
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 7.1.0

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  # iOS Main App
  EchoApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/EchoApp
    dependencies:
      - package: EchoCore
      - package: EchoUI
      - package: GoogleSignIn
      - target: EchoKeyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xianggui.echo.app
        INFOPLIST_FILE: iOS/EchoApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/EchoApp/EchoApp.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: iOS/EchoApp/Info.plist
      properties:
        CFBundleDisplayName: Echo
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSApplicationQueriesSchemes:
          - echo
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - echo
            CFBundleURLName: com.xianggui.echo.app
        NSMicrophoneUsageDescription: "Echo needs microphone access to transcribe your speech to text."
        NSSpeechRecognitionUsageDescription: "Echo uses speech recognition to convert your voice to text."
        GOOGLE_CLIENT_ID_IOS: "852034251160-krk9p201kbmfvbi40hpspvuiqji8fbau.apps.googleusercontent.com"
    entitlements:
      path: iOS/EchoApp/EchoApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.xianggui.echo.shared
        com.apple.developer.applesignin:
          - Default

  # iOS Keyboard Extension
  EchoKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/EchoKeyboard
    dependencies:
      - package: EchoCore
      - package: EchoUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xianggui.echo.app.keyboard
        INFOPLIST_FILE: iOS/EchoKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/EchoKeyboard/EchoKeyboard.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: iOS/EchoKeyboard/Info.plist
      properties:
        CFBundleDisplayName: Echo
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).KeyboardViewController"
    entitlements:
      path: iOS/EchoKeyboard/EchoKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.xianggui.echo.shared

  # macOS Menu Bar App
  EchoMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: macOS/EchoMac
    dependencies:
      - package: EchoCore
      - package: EchoUI
      - package: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xianggui.echo.mac
        INFOPLIST_FILE: macOS/EchoMac/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/EchoMac/EchoMac.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: J5Y8R5W53N
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    info:
      path: macOS/EchoMac/Info.plist
      properties:
        CFBundleDisplayName: Echo
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSUIElement: true
        NSMicrophoneUsageDescription: "Echo needs microphone access to transcribe your speech to text."
        NSInputMonitoringUsageDescription: "Echo needs input monitoring to detect global hotkeys."
        GOOGLE_CLIENT_ID_MAC: "852034251160-6bdpkhrdcv5or59ogk8nort09hqfessa.apps.googleusercontent.com"
    entitlements:
      path: macOS/EchoMac/EchoMac.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true
        com.apple.security.network.client: true
        com.apple.security.network.server: true
        com.apple.developer.applesignin:
          - Default

schemes:
  Echo:
    build:
      targets:
        EchoApp: all
        EchoKeyboard: all
    run:
      config: Debug
      executable: EchoApp
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  EchoMac:
    build:
      targets:
        EchoMac: all
    run:
      config: Debug
      executable: EchoMac
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
