name: Typeless
options:
  bundleIdPrefix: com.typeless
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

packages:
  TypelessCore:
    path: Packages/TypelessCore
  TypelessUI:
    path: Packages/TypelessUI

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  # iOS Main App
  TypelessApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/TypelessApp
    dependencies:
      - package: TypelessCore
      - package: TypelessUI
      - target: TypelessKeyboard
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typeless.app
        INFOPLIST_FILE: iOS/TypelessApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/TypelessApp/TypelessApp.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: iOS/TypelessApp/Info.plist
      properties:
        CFBundleDisplayName: Typeless
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSApplicationQueriesSchemes:
          - typeless
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - typeless
            CFBundleURLName: com.typeless.app
        NSMicrophoneUsageDescription: "Typeless needs microphone access to transcribe your speech to text."
        NSSpeechRecognitionUsageDescription: "Typeless uses speech recognition to convert your voice to text."
    entitlements:
      path: iOS/TypelessApp/TypelessApp.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.typeless.shared

  # iOS Keyboard Extension
  TypelessKeyboard:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: iOS/TypelessKeyboard
    dependencies:
      - package: TypelessCore
      - package: TypelessUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typeless.app.keyboard
        INFOPLIST_FILE: iOS/TypelessKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: iOS/TypelessKeyboard/TypelessKeyboard.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
    info:
      path: iOS/TypelessKeyboard/Info.plist
      properties:
        CFBundleDisplayName: Typeless
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionAttributes:
            IsASCIICapable: false
            PrefersRightToLeft: false
            PrimaryLanguage: en
            RequestsOpenAccess: true
          NSExtensionPointIdentifier: com.apple.keyboard-service
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).KeyboardViewController"
    entitlements:
      path: iOS/TypelessKeyboard/TypelessKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.typeless.shared

  # macOS Menu Bar App
  TypelessMac:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: macOS/TypelessMac
    dependencies:
      - package: TypelessCore
      - package: TypelessUI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typeless.mac
        INFOPLIST_FILE: macOS/TypelessMac/Info.plist
        CODE_SIGN_ENTITLEMENTS: macOS/TypelessMac/TypelessMac.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    info:
      path: macOS/TypelessMac/Info.plist
      properties:
        CFBundleDisplayName: Typeless
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSUIElement: true
        NSMicrophoneUsageDescription: "Typeless needs microphone access to transcribe your speech to text."
        NSInputMonitoringUsageDescription: "Typeless needs input monitoring to detect global hotkeys."
    entitlements:
      path: macOS/TypelessMac/TypelessMac.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true
        com.apple.security.network.client: true

schemes:
  Typeless:
    build:
      targets:
        TypelessApp: all
        TypelessKeyboard: all
    run:
      config: Debug
      executable: TypelessApp
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  TypelessMac:
    build:
      targets:
        TypelessMac: all
    run:
      config: Debug
      executable: TypelessMac
    test:
      config: Debug
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
