import Foundation
import CryptoKit

/// Decrypts AES-256-GCM encrypted Volcano API credentials at runtime
/// and seeds them into the Keychain via SecureKeyStore.
///
/// User-provided keys always take priority: `seedKeychainIfNeeded`
/// checks `hasKey` before writing, so it never overwrites.
///
/// ## Re-encryption
/// ```bash
/// swift scripts/embed_keys.swift \
///   --volcano-app-id "NEW_ID" \
///   --volcano-access-key "NEW_KEY" \
///   --volcano-resource-id "volc.bigasr.auc_turbo" \
///   --volcano-endpoint "wss://openspeech.bytedance.com/api/v3/sauc/bigmodel"
/// ```
/// Then paste the printed byte array below, replacing `encryptedPayload`.
public final class EmbeddedKeyProvider: Sendable {

    public static let shared = EmbeddedKeyProvider()

    // MARK: - HKDF Parameters (must match scripts/embed_keys.swift)

    private static let masterSecret = "echo-embedded-v1"
    private static let hkdfSalt = "com.xianggui.echo"
    private static let hkdfInfo = "aes-256-gcm-key"

    // MARK: - Key IDs

    private static let keyIds: [String] = [
        "volcano_app_id",
        "volcano_access_key",
        "volcano_resource_id",
        "volcano_endpoint"
    ]

    // MARK: - Encrypted Payload
    //
    // Generated by: swift scripts/embed_keys.swift --volcano-app-id ... --volcano-access-key ...
    // Run the script and paste the output here.
    // Format: Nonce (12 bytes) + Ciphertext (N bytes) + Tag (16 bytes)
    //
    // TODO: Replace with real bytes by running:
    //   swift scripts/embed_keys.swift \
    //     --volcano-app-id "6490217589" \
    //     --volcano-access-key "pYaGFt9q_xgejFQ-rZ9SVVa4hllXTamX" \
    //     --volcano-resource-id "volc.bigasr.auc_turbo" \
    //     --volcano-endpoint "wss://openspeech.bytedance.com/api/v3/sauc/bigmodel"
    private static let encryptedPayload: [UInt8] = [
        0x9B, 0xEF, 0x37, 0x24, 0x9D, 0xAB, 0x92, 0x56, 0x08, 0x2A, 0x42, 0x70, 0xD2, 0x0B, 0x1F, 0x43,
        0x7E, 0xB1, 0x15, 0x00, 0x5B, 0x7F, 0x1D, 0x73, 0x43, 0x97, 0xE6, 0x35, 0x18, 0xF2, 0xA1, 0xA4,
        0x7A, 0x02, 0x8F, 0x06, 0xD6, 0x14, 0x65, 0x4A, 0xCD, 0xF9, 0x73, 0xC2, 0xEF, 0x8A, 0x7F, 0xAF,
        0x09, 0x93, 0x69, 0xF6, 0x89, 0xB6, 0x2A, 0xC4, 0x75, 0x61, 0xCA, 0xB6, 0x5C, 0x4A, 0xF3, 0xB1,
        0x12, 0xE8, 0xCB, 0xC7, 0xEC, 0x52, 0x89, 0x05, 0xA7, 0xBD, 0x04, 0x0E, 0x48, 0xC9, 0x65, 0x14,
        0x4B, 0x15, 0x62, 0x34, 0x9B, 0xF2, 0x7D, 0xB0, 0x1E, 0x58, 0x0A, 0x56, 0x6D, 0xE2, 0xF9, 0xC4,
        0x88, 0x19, 0xA6, 0x58, 0xC6, 0x82, 0xAF, 0xA6, 0xCF, 0xAB, 0x83, 0x84, 0x5E, 0x32, 0x5C, 0x50,
        0x7E, 0xEE, 0xDB, 0x84, 0x29, 0x9C, 0x60, 0xB8, 0xF4, 0xCB, 0x30, 0xE1, 0xBC, 0xA2, 0x97, 0x57,
        0x45, 0x6A, 0x67, 0x6C, 0x9D, 0xA9, 0xF6, 0xA7, 0xF3, 0xDE, 0xD3, 0x86, 0xEC, 0x63, 0x1A, 0x68,
        0x1C, 0xC6, 0x4E, 0x79, 0xA7, 0x9D, 0x97, 0x75, 0x9F, 0xD3, 0xDD, 0x18, 0x0F, 0xF6, 0x0E, 0x72,
        0x24, 0x87, 0xF1, 0x35, 0xF7, 0x21, 0xCE, 0x88, 0x9F, 0x11, 0x4D, 0x32, 0xA5, 0x28, 0x20, 0x57,
        0x72, 0x0D, 0x08, 0x53, 0xA5, 0xE3, 0x51, 0x70, 0xBC, 0xEF, 0x57, 0xCC, 0xA8, 0x51, 0x14, 0x51,
        0x67, 0xF8, 0x18, 0x43, 0x2B, 0x1A, 0x8D, 0x6F, 0xCC, 0x70, 0xC3, 0xDF, 0xEB, 0x6F, 0x86, 0x2C,
        0xD0, 0x4B, 0xAF, 0xDC, 0x65, 0x40, 0xFE, 0xFC, 0xE8, 0x1C, 0x13, 0x49, 0xD1, 0xD6, 0xAA, 0xCB,
        0x9F, 0xF1, 0xC4, 0xE7, 0x35, 0xD7, 0x1E, 0x59, 0xF2, 0xBA, 0x84, 0x0F, 0xBD, 0x95, 0x3F, 0x75
    ]

    // MARK: - Mutable State

    /// Tracks whether seeding has already been attempted this process lifetime.
    nonisolated(unsafe) private static var didSeed = false
    private static let seedLock = NSLock()

    // MARK: - Init

    private init() {}

    // MARK: - Public API

    /// Decrypt embedded keys and write any missing ones to the Keychain.
    ///
    /// Safe to call multiple times; only the first invocation performs work.
    /// Never overwrites user-provided keys.
    ///
    /// - Parameter keyStore: The `SecureKeyStore` instance to write into.
    public func seedKeychainIfNeeded(keyStore: SecureKeyStore = SecureKeyStore()) {
        Self.seedLock.lock()
        let alreadySeeded = Self.didSeed
        if !alreadySeeded {
            Self.didSeed = true
        }
        Self.seedLock.unlock()

        guard !alreadySeeded else { return }

        guard !Self.encryptedPayload.isEmpty else { return }

        guard let decryptedKeys = decryptPayload() else { return }

        for keyId in Self.keyIds {
            guard let value = decryptedKeys[keyId], !value.isEmpty else {
                continue
            }

            if keyStore.hasKey(for: keyId) {
                continue
            }

            do {
                try keyStore.store(key: value, for: keyId)
            } catch {
                // Silently skip — the user can still enter keys manually.
                // Logging is intentionally omitted to avoid leaking key metadata.
            }
        }
    }

    // MARK: - Decryption

    private func decryptPayload() -> [String: String]? {
        let payload = Data(Self.encryptedPayload)

        guard payload.count > 28 else {
            // Minimum: 12 (nonce) + 0 (ciphertext) + 16 (tag) = 28
            return nil
        }

        let derivedKey = Self.deriveKey()

        do {
            let sealedBox = try AES.GCM.SealedBox(combined: payload)
            let plaintext = try AES.GCM.open(sealedBox, using: derivedKey)
            let decoded = try JSONSerialization.jsonObject(with: plaintext) as? [String: String]
            return decoded
        } catch {
            return nil
        }
    }

    private static func deriveKey() -> SymmetricKey {
        let inputKey = SymmetricKey(data: Data(masterSecret.utf8))
        let salt = Data(hkdfSalt.utf8)
        let info = Data(hkdfInfo.utf8)

        return HKDF<SHA256>.deriveKey(
            inputKeyMaterial: inputKey,
            salt: salt,
            info: info,
            outputByteCount: 32
        )
    }
}
